Data Preprocessing

Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Import dataset

In [2]:
dataset = pd.read_csv('cancer_reg.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(dataset.isnull().any())

avganncount                False
avgdeathsperyear           False
incidencerate              False
medincome                  False
popest2015                 False
povertypercent             False
studypercap                False
binnedinc                  False
medianage                  False
medianagemale              False
medianagefemale            False
geography                  False
percentmarried             False
pctnohs18_24               False
pcths18_24                 False
pctsomecol18_24             True
pctbachdeg18_24            False
pcths25_over               False
pctbachdeg25_over          False
pctemployed16_over          True
pctunemployed16_over       False
pctprivatecoverage         False
pctprivatecoveragealone     True
pctempprivcoverage         False
pctpubliccoverage          False
pctpubliccoveragealone     False
pctwhite                   False
pctblack                   False
pctasian                   False
pctotherrace               False
pctmarried

Taking care of missing data

In [4]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 15:32])
X[:, 15:32]=imputer.transform(X[:, 15:32])
print(X[:, 15])

[42.1 64.0 40.977034120734906 ... 33.3 40.977034120734906 43.9]


Handling categorical data

In [5]:
#delete geography column
X = np.delete(X, [11], axis=1)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 0.0 ... 1.843478533 52.85607588 6.118831029]
 [0.0 0.0 0.0 ... 3.741351531 45.37250044 4.333095578]
 [0.0 0.0 0.0 ... 2.747358309 54.44486837 3.729487817]
 ...
 [0.0 0.0 0.0 ... 5.680705191 55.15394913 7.80919168]
 [0.0 0.0 0.0 ... 2.131790471 58.48423194 7.582938389]
 [0.0 0.0 1.0 ... 1.356457444 56.04024208 8.981723238]]


Splitting the dataset into the training set and test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 1)

Training the Multiple Linear Regression model on the Training set

In [7]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

Predict the Test set results

In [8]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[185.54 175.9 ]
 [154.7  160.4 ]
 [187.35 195.8 ]
 ...
 [192.36 203.2 ]
 [181.9  212.  ]
 [182.46 161.7 ]]
